const SUPABASE_URL="https://pmshdzafuaadxbkzzvdj.supabase.co",SUPABASE_KEY="sb_publishable_yWRdbcIpWXniK9fe31KchQ_3T0zGdpb",db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),LEAFGPT_API="https://leaf-gpt.vercel.app/api/chat";
const $=id=>document.getElementById(id),form=$("chatForm"),input=$("messageInput"),chat=$("chat"),welcome=$("welcome"),countEl=$("messageCount"),progress=$("progressBar"),historyList=$("historyList"),accountButton=$("accountButton"),accountName=$("accountName"),accountStatus=$("accountStatus"),authOverlay=$("authOverlay"),authClose=$("authClose"),authForm=$("authForm"),authEmail=$("authEmail"),authPassword=$("authPassword"),authTitle=$("authTitle"),authSubmit=$("authSubmit"),authSwitch=$("authSwitch"),authMessage=$("authMessage"),logoutButton=$("logoutButton");
let currentUser=null,currentChatId=null,messages=[],generating=false,mode="login",count=0,chatsLoadVersion=0;
if(!matchMedia("(prefers-reduced-motion: reduce)").matches){const intro=$("intro"),leaf=$("introLeaf"),word=$("introWord"),reverseLetters=[...word.querySelectorAll(".chain-letter")].reverse();setTimeout(()=>leaf.classList.add("fly"),1050);setTimeout(()=>{leaf.classList.remove("fly");leaf.classList.add("after-hit");reverseLetters.forEach((letter,index)=>{const delay=index*170;if(reverseLetters[index+1])setTimeout(()=>reverseLetters[index+1].classList.add("prepare-hit"),delay+110);setTimeout(()=>letter.classList.add("hit"),delay)});const duration=reverseLetters.length*170;setTimeout(()=>{document.body.classList.add("intro-finished");intro.classList.add("out")},duration+300);setTimeout(()=>intro.remove(),duration+1100)},1690)}else{document.body.classList.add("intro-finished");$("intro")?.remove()}
input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,140)+"px"});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if(!generating)form.requestSubmit()}});
$("newChatButton")?.addEventListener("click",startNewChat);$("newChatIcon")?.addEventListener("click",startNewChat);
function startNewChat(){currentChatId=null;messages=[];chat.innerHTML="";welcome.style.display="";input.value="";markActiveChat();input.focus()}
function addMessage(text,type){const e=document.createElement("div");e.className="message "+type;e.textContent=text;chat.appendChild(e);chat.scrollTop=chat.scrollHeight}
function titleFor(t){t=t.replace(/\s+/g," ").trim();return t.length>34?t.slice(0,34)+"…":t||"Nowy czat"}
async function saveMessage(role,content){if(currentUser&&currentChatId){const{error}=await db.from("messages").insert({chat_id:currentChatId,user_id:currentUser.id,role,content});if(error)console.error(error)}}
form.addEventListener("submit",async e=>{e.preventDefault();if(generating)return;const text=input.value.trim();if(!text)return;welcome.style.display="none";if(currentUser&&!currentChatId){const{data,error}=await db.from("chats").insert({user_id:currentUser.id,title:titleFor(text)}).select().single();if(!error){currentChatId=data.id;await loadChats()}else console.error(error)}addMessage(text,"user");messages.push({role:"user",content:text});await saveMessage("user",text);count=(count+1)%100;countEl.textContent=count;progress.style.width=count+"%";input.value="";generating=true;const thinking=document.createElement("div");thinking.className="message bot thinking";thinking.textContent="LeafGPT myśli... 🍃";chat.appendChild(thinking);try{const r=await fetch(LEAFGPT_API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages})}),d=await r.json();thinking.remove();if(!r.ok){addMessage(d.error||"Wystąpił błąd LeafGPT.","bot");generating=false;return}const reply=d.reply||"Nie udało mi się wygenerować odpowiedzi.";addMessage(reply,"bot");messages.push({role:"assistant",content:reply});await saveMessage("assistant",reply);if(currentUser)await loadChats()}catch(err){thinking.remove();addMessage("Nie udało się połączyć z serwerem LeafGPT.","bot");console.error(err)}generating=false});
async function loadChats(){const v=++chatsLoadVersion;if(!currentUser){historyList.replaceChildren();return}const uid=currentUser.id,{data,error}=await db.from("chats").select("id,title,updated_at").eq("user_id",uid).order("updated_at",{ascending:false});if(v!==chatsLoadVersion||!currentUser||currentUser.id!==uid)return;if(error)return console.error(error);const f=document.createDocumentFragment();for(const item of data||[]){const row=document.createElement("div");row.className="history-chat";row.dataset.chatId=item.id;if(item.id===currentChatId)row.classList.add("active-chat");const open=document.createElement("button");open.className="history-chat-open";open.innerHTML="<span>○</span>";const title=document.createElement("span");title.className="history-chat-title";title.textContent=item.title;open.append(title);open.onclick=()=>openChat(item.id);const mb=document.createElement("button");mb.className="history-menu-button";mb.textContent="⋯";const menu=document.createElement("div");menu.className="history-menu hidden";const ren=document.createElement("button");ren.textContent="Zmień nazwę";const del=document.createElement("button");del.textContent="Usuń czat";del.className="delete-chat-button";menu.append(ren,del);mb.onclick=e=>{e.stopPropagation();menu.classList.toggle("hidden")};ren.onclick=async e=>{e.stopPropagation();const n=prompt("Nowa nazwa rozmowy:",item.title)?.trim();if(n){await db.from("chats").update({title:n.slice(0,60)}).eq("id",item.id).eq("user_id",uid);await loadChats()}};del.onclick=async e=>{e.stopPropagation();if(confirm(`Usunąć rozmowę "${item.title}"?`)){await db.from("chats").delete().eq("id",item.id).eq("user_id",uid);if(currentChatId===item.id)startNewChat();await loadChats()}};row.append(open,mb,menu);f.append(row)}historyList.replaceChildren(f)}
async function openChat(id){if(!currentUser||generating)return;currentChatId=id;chat.innerHTML="";messages=[];welcome.style.display="none";const{data,error}=await db.from("messages").select("role,content,created_at").eq("chat_id",id).eq("user_id",currentUser.id).order("created_at",{ascending:true});if(error)return console.error(error);for(const m of data||[]){messages.push({role:m.role,content:m.content});addMessage(m.content,m.role==="assistant"?"bot":"user")}markActiveChat()}
function markActiveChat(){document.querySelectorAll(".history-chat").forEach(e=>e.classList.toggle("active-chat",e.dataset.chatId===currentChatId))}
accountButton.onclick=()=>{authOverlay.classList.remove("hidden");renderModal()};authClose.onclick=()=>authOverlay.classList.add("hidden");authSwitch.onclick=()=>{mode=mode==="login"?"register":"login";renderModal()};
function renderModal(){if(currentUser){authTitle.textContent="Twoje konto";authForm.classList.add("hidden");authSwitch.classList.add("hidden");logoutButton.classList.remove("hidden");authMessage.textContent=currentUser.email||"";return}authForm.classList.remove("hidden");authSwitch.classList.remove("hidden");logoutButton.classList.add("hidden");authTitle.textContent=mode==="login"?"Zaloguj się":"Utwórz konto";authSubmit.textContent=mode==="login"?"Zaloguj się":"Zarejestruj się";authSwitch.textContent=mode==="login"?"Nie masz konta? Zarejestruj się":"Masz już konto? Zaloguj się"}
authForm.onsubmit=async e=>{e.preventDefault();const email=authEmail.value.trim(),password=authPassword.value;authSubmit.disabled=true;const r=mode==="register"?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});authSubmit.disabled=false;if(r.error){authMessage.textContent=r.error.message;return}if(mode==="register"&&!r.data.session)authMessage.textContent="Konto utworzone. Sprawdź e-mail.";else authOverlay.classList.add("hidden")};
logoutButton.onclick=async()=>{await db.auth.signOut();startNewChat();historyList.replaceChildren();authOverlay.classList.add("hidden")};
async function renderUser(u){currentUser=u;if(u){accountName.textContent=u.email?.split("@")[0]||"Użytkownik";accountStatus.textContent=u.email||"Zalogowano";await loadChats()}else{accountName.textContent="Użytkownik";accountStatus.textContent="Zaloguj się, aby zapisywać rozmowy";historyList.replaceChildren()}renderModal()}
db.auth.onAuthStateChange((_e,s)=>renderUser(s?.user??null));